pipeline {
     agent any
    stages {
        stage('checkout'){
            steps{
                git branch: 'main', url: 'https://github.com/manojgk28/ManojGK.git'
            }
        }
        stage('Build') {
            steps {
                sh 'mvn package'
            }
        }
        
                }
            }
        
        
        
